fabric 1.20.1 functional port
TeamTwilight/twilightforest-fabric pull request #222
Opened 2024-11-07 16:39 UTC by marlester-dev

2024-11-07 16:48 UTC, Tamaized commented on src/main/java/twilightforest/ASMHooks.java
> +		return o || (fenceState.is(TFBlocks.WROUGHT_IRON_FENCE.get()) && fenceState.getValue(WroughtIronFenceBlock.POST) != Boolean.FALSE);
Logic doesn't match Forge, is there a reason?
https://github.com/TeamTwilight/twilightforest/blob/1.20.1/src/main/java/twilightforest/ASMHooks.java#L333

2024-11-07 17:33 UTC, Tamaized requested changes

2024-11-07 17:33 UTC, Tamaized commented on src/main/java/twilightforest/TFMagicMapData.java
> +				float f2 = (float) featureId / 8 / 8.0F;
Remove these casts, they break the math.

2024-11-07 17:33 UTC, Tamaized commented on src/main/java/twilightforest/TFMagicMapData.java
> +				float f4 = ((float) featureId / 8 + 1) / 8.0F;
Here too

2024-11-07 17:38 UTC, marlester-dev commented on src/main/java/twilightforest/TFMagicMapData.java
> +				float f2 = (float) featureId / 8 / 8.0F;
Hm. I don't remember me adding them. Fixed anyway.

2024-11-07 17:43 UTC, Tamaized commented on src/main/java/twilightforest/TwilightForestMod.java
> +	public void registerWoodPalettes() {
How come these arent organized into a helper method like they are in the forge codebase?
https://github.com/TeamTwilight/twilightforest/blob/1.20.1/src/main/java/twilightforest/TwilightForestMod.java#L137

2024-11-07 17:48 UTC, marlester-dev commented on src/main/java/twilightforest/TwilightForestMod.java
> +	public void registerWoodPalettes() {
It seems like forge's DeferredRegister registers everything automatically, but portinglib's LazyRegistrar isn't doing it
I think about creating a custom registrar to handle this

2024-11-07 17:52 UTC, Tamaized commented on src/main/java/twilightforest/TwilightForestMod.java
> +	public void registerWoodPalettes() {
I meant, why is it in the main mod class and not in WoodPalettes. It doesn't have anything to do with forge vs fabric. It's just an organization issue.

2024-11-07 17:57 UTC, marlester-dev commented on src/main/java/twilightforest/TwilightForestMod.java
> +	public void registerWoodPalettes() {
> I meant, why is it in the main mod class and not in WoodPalettes. It doesn't have anything to do with forge vs fabric. It's just an organization issue.

Makes sense

2024-11-07 17:59 UTC, Tamaized commented
Have you confirmed that every single method in AsmHooks gets triggered?
I normally test by placing a breakpoint in each method and removing them one by one as they get hit.

2024-11-07 18:05 UTC, Tamaized requested changes

2024-11-07 18:05 UTC, Tamaized commented on src/main/java/twilightforest/block/ForceFieldBlock.java
> +		this.registerDefaultState(this.getStateDefinition().any().setValue(WATERLOGGED, false).setValue(AXIS, Direction.Axis.Y)
??
https://github.com/TeamTwilight/twilightforest/blob/1.20.1/src/main/java/twilightforest/block/ForceFieldBlock.java#L61

2024-11-07 18:05 UTC, Tamaized commented on src/main/java/twilightforest/block/ForceFieldBlock.java
> +		this.registerDefaultState(this.getStateDefinition().any().setValue(WATERLOGGED, false).setValue(AXIS, Direction.Axis.Y)
There's no AXIS property in the force codebase.

2024-11-07 18:07 UTC, Tamaized commented on src/main/java/twilightforest/block/ForceFieldBlock.java
> +		this.registerDefaultState(this.getStateDefinition().any().setValue(WATERLOGGED, false).setValue(AXIS, Direction.Axis.Y)
In fact, this entire class doesn't match at all.

2024-11-07 18:14 UTC, marlester-dev commented on src/main/java/twilightforest/block/ForceFieldBlock.java
> +		this.registerDefaultState(this.getStateDefinition().any().setValue(WATERLOGGED, false).setValue(AXIS, Direction.Axis.Y)
I guess I decided to use old force fields because I struggled with making the new ones work. I will try it one more time

2024-11-07 18:16 UTC, Tamaized commented on src/main/java/twilightforest/block/ForceFieldBlock.java
> +		this.registerDefaultState(this.getStateDefinition().any().setValue(WATERLOGGED, false).setValue(AXIS, Direction.Axis.Y)
There must be full parity with the 1.20.1 codebase.

2024-11-07 18:37 UTC, marlester-dev commented
> Have you confirmed that every single method in AsmHooks gets triggered? I normally test by placing a breakpoint in each method and removing them one by one as they get hit.

The most of them are getting hit, though I will need to check the yellow ones tomorrow (book, lead, cloud, mountFix, getPlayerPOVHitResultForReach, renderMultiparts):
![3725742](https://github.com/user-attachments/assets/552c7733-7681-4118-9ea5-4206bb37850e)

2024-11-07 18:38 UTC, marlester-dev commented on src/main/java/twilightforest/block/ForceFieldBlock.java
> +		this.registerDefaultState(this.getStateDefinition().any().setValue(WATERLOGGED, false).setValue(AXIS, Direction.Axis.Y)
alright, I guess I will handle that giving that I have more idea of the code base now

2024-11-10 10:13 UTC, marlester-dev commented
wait a moment.. why is asm using Java.type('net.minecraftforge.coremod.api.ASMAPI') if we are in fabric

2024-11-10 10:15 UTC, marlester-dev commented
bruh was it broken since 1.18

EDIT: I will be inactive for some time, I will let @IAFEnvoy work on this

2024-11-24 19:42 UTC, merged